-- Agent profile fields for "resume" + avatar
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "fullName" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "nationality" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "specialties" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "hobbies" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "age" INTEGER;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "contact" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "workExperience" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "avatarSvg" TEXT;

